markdown:         rdiscount
pygments:         true
paginate:         5
permalink:        /blog/:year/:month/:day/:title/
timezone:         Asia/Shanghai

title:            凤舞清歌
description:      Blog by silverzhao
url:              http://silver-zhao.github.io
author:
    name:         silverzhao
    email:        silverzhaojr@gmail.com
    github:       https://github.com/silver-zhao
about:            Hello, I'm Jason Zhao.
copyright:        Copyright © 2013 silverzhao
blog_name:        凤舞清歌
blog_desc:        起舞弄清影，何似在人间。
default_motto:    梨花院落溶溶月，柳絮池塘淡淡风。

disqus:           silverzhao
